name: tests
# Since this package must be tested inside a Laravel application this workflow does the following:
# Create a fresh Laravel host app
# Checkout package into host/packages/Ajthinking/PHPFileManipulator
# Add the package in host composer.json repositories section
# Require the package using @dev
# Publishing config
# Running tests: vendor/phpunit/phpunit/phpunit packages/Ajthinking/PHPFileManipulator/tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install host app
      run: composer create-project --prefer-dist laravel/laravel host
      
    - name: Checkout the package
      uses: actions/checkout@v2
      with:
        path: host/packages/Ajthinking/PHPFileManipulator

    - name: Add composer.json repository
      working-directory: ./host      
      run: composer config repositories.php-file-manipulator path "/home/runner/work/php-file-manipulator/php-file-manipulator/host/packages/Ajthinking/PHPFileManipulator"

    - name: Require the package
      working-directory: ./host
      run: composer require ajthinking/php-file-manipulator @dev

    - name: Publish things
      working-directory: ./host
      run: php artisan vendor:publish --provider="PHPFileManipulator\ServiceProvider"

    - name: Run tests
      working-directory: ./host      
      run: vendor/phpunit/phpunit/phpunit packages/Ajthinking/PHPFileManipulator/tests
